easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
        - App\Entity\Rubrique
        - App\Entity\Categorie
        - App\Entity\SousCategorie
        - App\Entity\Page
        - App\Entity\User
